name: Ubuntu Release

on:
  push:
    branches:
      - '**'
  release:
    types: [published]

jobs:
  build-ubuntu:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout source
      uses: actions/checkout@v4
      with:
        submodules: false

    - name: Use CMake 3.24
      uses: lukka/get-cmake@latest
      with:
        cmakeVersion: "3.24.0"

    - name: Setup JDK
      uses: actions/setup-java@v4
      with:
        distribution: "liberica"
        java-version: "21"

    - name: Install dependencies via apt-get and cache
      uses: apt-get-install/apt-get-install@v1
      id: install-and-cache
      with:
        packages: build-essential libboost-all-dev libssl-dev libzmq3-dev libsodium-dev unbound libunbound-dev liblzma-dev libreadline-dev libexpat1-dev qttools5-dev libhidapi-dev libusb-1.0-0-dev libprotobuf-dev doxygen graphviz libtool gperf libevent-dev pkg-config
        cache-key: ${{ runner.os }}-apt-dependencies-v1


#    - name: Configure and build (with debug flags)
#      run: |
#        mkdir -p build-ubuntu
#        cd build-ubuntu
#        cmake .. -DCMAKE_BUILD_TYPE=Release -DBUILD_STATIC=ON -DCMAKE_FIND_DEBUG_MODE=ON --trace-expand
#        cmake --build . --parallel 1
#      env:
#        ACTIONS_STEP_DEBUG: true

#    - name: Configure and build
#      run: |
#        mkdir -p build-ubuntu
#        cd build-ubuntu
#        cmake .. -DCMAKE_BUILD_TYPE=Release -DBUILD_STATIC=ON
#        cmake --build . --parallel 1
#
#    - name: Prepare and package release artifacts
#      if: github.event_name == 'release'
#      run: |
#        # Create a directory for the final artifacts
#        mkdir -p dist/ubuntu-22.04
#        
#        # Copy the monero-java library to the distribution directory
#        cp build-ubuntu/libmonero-java.so dist/ubuntu-22.04/
#        
#        # Create zip and tar.gz archives from the distribution directory.
#        # This is more robust as it's run from the project root.
#        zip -r dist/ubuntu-22.04/monero-java_ubuntu.zip dist/ubuntu-22.04/
#        tar -czvf dist/ubuntu-22.04/monero-java_ubuntu.tar.gz -C dist/ubuntu-22.04 .
#          
#    - name: Upload Release Assets
#      if: github.event_name == 'release'
#      uses: actions/upload-release-asset@v1
#      env:
#        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#      with:
#        upload_url: ${{ github.event.release.upload_url }}
#        asset_path: ./dist/ubuntu-22.04/monero-java_ubuntu.zip
#        asset_name: monero-java_ubuntu.zip
#        asset_content_type: application/zip
#    
#    - name: Upload tar.gz Release Asset
#      if: github.event_name == 'release'
#      uses: actions/upload-release-asset@v1
#      env:
#        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#      with:
#        upload_url: ${{ github.event.release.upload_url }}
#        asset_path: ./dist/ubuntu-22.04/monero-java_ubuntu.tar.gz
#        asset_name: monero-java_ubuntu.tar.gz
#        asset_content_type: application/gzip
